-- Mega Youth Family Gathering 2026 - Supabase database
-- SAFE RE-RUN INSTALL / UPGRADE
-- This file may be run again on an existing Supabase project.
-- It does NOT delete registrations, finance data, or admin users.
-- Existing policies managed by this script are dropped/recreated by name.


create extension if not exists pgcrypto;

create sequence if not exists public.registration_number_seq start 1;

create table if not exists public.event_settings (
  id integer primary key default 1 check (id = 1),
  event_name text not null default 'Mega Youth Family Gathering 2026',
  event_date text not null default 'To be announced',
  venue text not null default 'To be announced',
  total_seats integer not null default 500 check (total_seats >= 0),
  fees jsonb not null default '{"Infant":0,"Child":10,"Teenager":10,"Adult":10,"Senior":10}'::jsonb,
  whatsapp_group_link text not null default '',
  confirmation_email_enabled boolean not null default false,
  email_subject text not null default 'Mega Youth Family Gathering 2026 – Registration Confirmation',
  logo_url text not null default 'logo.svg',
  promo_code text not null default 'FREE2026',
  email_body text not null default 'Assalamu Alaikum,\n\nYour registration for {{EVENT_NAME}} has been received.\n\nRegistration ID: {{REGISTRATION_ID}}\nMain Participant: {{MAIN_PARTICIPANT}}\nTotal Participants: {{TOTAL_PARTICIPANTS}}\nTotal Amount: SAR {{TOTAL_AMOUNT}}\nPayment Status: {{PAYMENT_STATUS}}\nRegistration Status: {{REGISTRATION_STATUS}}\nEvent Date: {{EVENT_DATE}}\nVenue: {{VENUE}}\n\nJazakAllahu Khairan.',
  updated_at timestamptz not null default now()
);

insert into public.event_settings (id) values (1)
on conflict (id) do nothing;

create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.registrations (
  registration_id text primary key,
  registration_number bigint not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  main_participant text not null,
  nationality text not null check (nationality in ('Sri Lankan','Indian')),
  gender text check (gender in ('Male','Female') or gender is null),
  main_age_group text not null check (main_age_group in ('Infant','Child','Teenager','Adult','Senior')),
  mobile text not null,
  email text not null,
  email_token uuid not null default gen_random_uuid(),
  participants jsonb not null default '[]'::jsonb,
  fee_breakdown jsonb not null default '[]'::jsonb,
  total_participants integer not null check (total_participants >= 1),
  entry_fee numeric(12,2) not null default 0,
  total_amount numeric(12,2) not null default 0,
  payment_method text not null default 'Cash' check (payment_method in ('Cash','Promo Code')),
  promo_code_used text not null default '',
  discount_amount numeric(12,2) not null default 0,
  rating smallint check (rating is null or (rating between 1 and 5)),
  feedback_comment text not null default '',
  seat_status text not null,
  payment_status text not null,
  registration_status text not null,
  ticket_status text not null,
  checked_in boolean not null default false,
  checked_in_at timestamptz,
  qr_data text not null
);

create index if not exists registrations_mobile_idx on public.registrations(mobile);
create index if not exists registrations_created_at_idx on public.registrations(created_at desc);
create index if not exists registrations_seat_status_idx on public.registrations(seat_status);
create index if not exists registrations_payment_status_idx on public.registrations(payment_status);

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid references auth.users(id) on delete set null,
  action text not null,
  details text not null default ''
);
create index if not exists admin_logs_created_at_idx on public.admin_logs(created_at desc);

-- Security helper
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    where au.id = auth.uid()
      and au.role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- First-admin bootstrap: the first authenticated user can become Admin automatically.
-- Once any Admin exists, only an existing Admin can continue using Admin features.
create or replace function public.bootstrap_first_admin()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'You must be signed in.';
  end if;

  -- Prevent two first-users from bootstrapping at the same time.
  perform pg_advisory_xact_lock(84726119);

  if exists (select 1 from public.admin_users where id = auth.uid()) then
    return jsonb_build_object('ok', true, 'role', 'admin', 'created', false);
  end if;

  if exists (select 1 from public.admin_users) then
    raise exception 'An Admin account already exists. Sign in with an existing Admin account.';
  end if;

  insert into public.admin_users(id, role)
  values (auth.uid(), 'admin');

  insert into public.admin_logs(user_id, action, details)
  values (auth.uid(), 'BOOTSTRAP_ADMIN', 'First authenticated user was granted Admin access.');

  return jsonb_build_object('ok', true, 'role', 'admin', 'created', true);
end;
$$;

revoke all on function public.bootstrap_first_admin() from public;
grant execute on function public.bootstrap_first_admin() to authenticated;

-- Availability helper
create or replace function public.get_availability()
returns jsonb
language sql
security definer
set search_path = public
as $$
  with stats as (
    select
      coalesce(sum(total_participants) filter (where seat_status in ('Reserved – Payment Pending','Confirmed')), 0)::int as occupied,
      coalesce(sum(total_participants) filter (where seat_status = 'Confirmed'), 0)::int as confirmed,
      coalesce(sum(total_participants) filter (where seat_status = 'Pending'), 0)::int as waiting
    from public.registrations
  )
  select jsonb_build_object(
    'totalSeats', es.total_seats,
    'reservedSeats', stats.occupied,
    'confirmedSeats', stats.confirmed,
    'waitingParticipants', stats.waiting,
    'availableSeats', greatest(es.total_seats - stats.occupied, 0)
  )
  from public.event_settings es cross join stats
  where es.id = 1;
$$;

grant execute on function public.get_availability() to anon, authenticated;

create or replace function public.get_public_settings()
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object('settings',jsonb_build_object('eventName',es.event_name,'eventDate',es.event_date,'venue',es.venue,'totalSeats',es.total_seats,'fees',es.fees,'logoUrl',es.logo_url,'whatsappGroupLink',es.whatsapp_group_link,'confirmationEmailEnabled',es.confirmation_email_enabled,'emailSubject',es.email_subject,'emailBody',es.email_body),'availability',public.get_availability())
  from public.event_settings es where es.id=1;
$$;
grant execute on function public.get_public_settings() to anon, authenticated;

-- Public registration RPC. The event row is locked during seat calculation so two users
-- cannot reserve the same seat capacity at the same time.
create or replace function public.create_registration(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  es public.event_settings;
  reg_no bigint;
  reg_id text;
  main_name text;
  nationality text;
  main_gender text;
  main_age text;
  mobile text;
  email text;
  extras jsonb;
  fee_breakdown jsonb := '[]'::jsonb;
  total_people integer := 1;
  total_before_discount numeric(12,2) := 0;
  total_amount numeric(12,2) := 0;
  person_fee numeric(12,2) := 0;
  discount_amount numeric(12,2) := 0;
  extra jsonb;
  occupied integer := 0;
  seat_status_value text;
  payment_status_value text := 'Payment Pending';
  registration_status_value text;
  ticket_status_value text := 'Not Valid';
  qr_text text;
  promo_input text;
  promo_valid boolean := false;
  payment_method_value text := 'Cash';
  rating_value smallint;
  feedback_value text;
  rec public.registrations;
begin
  main_name := trim(coalesce(p_data->>'mainParticipant',''));
  nationality := coalesce(p_data->>'nationality','');
  main_gender := coalesce(p_data->>'gender','');
  main_age := coalesce(p_data->>'mainAgeGroup','');
  mobile := regexp_replace(coalesce(p_data->>'mobile',''), '[^0-9]', '', 'g');
  email := trim(coalesce(p_data->>'email',''));
  extras := coalesce(p_data->'participants','[]'::jsonb);
  promo_input := upper(trim(coalesce(p_data->>'promoCode','')));
  rating_value := nullif((p_data->>'rating')::int,0);
  feedback_value := left(trim(coalesce(p_data->>'feedbackComment','')),1000);

  if main_name = '' then raise exception 'Please enter the main participant name.'; end if;
  if nationality not in ('Sri Lankan','Indian') then raise exception 'Please select nationality.'; end if;
  if main_gender not in ('Male','Female') then raise exception 'Please select gender.'; end if;
  if main_age not in ('Infant','Child','Teenager','Adult','Senior') then raise exception 'Please select the main participant age group.'; end if;
  if length(mobile)=9 then mobile:='0'||mobile; end if;
  if mobile !~ '^0[0-9]{9}$' then raise exception 'Mobile number must contain exactly 10 digits and start with 0.'; end if;
  if email !~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then raise exception 'Please enter a valid email address.'; end if;
  if jsonb_typeof(extras) <> 'array' then raise exception 'Additional participants must be an array.'; end if;
  if rating_value is not null and (rating_value < 1 or rating_value > 5) then raise exception 'Rating must be between 1 and 5 stars.'; end if;

  select * into es from public.event_settings where id=1 for update;
  if not found then raise exception 'Event settings are not available.'; end if;

  if promo_input <> '' then
    if upper(trim(coalesce(es.promo_code,''))) <> '' and promo_input = upper(trim(es.promo_code)) then
      promo_valid := true;
      payment_method_value := 'Promo Code';
    else
      raise exception 'The Promo Code is invalid.';
    end if;
  end if;

  if not promo_valid and coalesce(p_data->>'cashConfirmed','false') <> 'true' then
    raise exception 'Please confirm the cash payment or enter a valid Free Promo Code.';
  end if;

  person_fee := coalesce((es.fees ->> main_age)::numeric,0);
  total_before_discount := person_fee;
  fee_breakdown := fee_breakdown || jsonb_build_object('participant',1,'relation','Main Participant','ageGroup',main_age,'amount',person_fee);

  for extra in select value from jsonb_array_elements(extras) loop
    total_people := total_people + 1;
    if coalesce(extra->>'relation','') = '' or coalesce(extra->>'gender','') not in ('Male','Female') or coalesce(extra->>'ageGroup','') not in ('Infant','Child','Teenager','Adult','Senior') then
      raise exception 'Please complete participant row %.', total_people;
    end if;
    person_fee := coalesce((es.fees ->> (extra->>'ageGroup'))::numeric,0);
    total_before_discount := total_before_discount + person_fee;
    fee_breakdown := fee_breakdown || jsonb_build_object('participant',total_people,'relation',extra->>'relation','gender',extra->>'gender','ageGroup',extra->>'ageGroup','amount',person_fee);
  end loop;

  discount_amount := case when promo_valid then total_before_discount else 0 end;
  total_amount := greatest(total_before_discount - discount_amount,0);

  select coalesce(sum(total_participants),0)::int into occupied
  from public.registrations
  where seat_status in ('Reserved – Payment Pending','Confirmed');

  if occupied + total_people <= es.total_seats then
    if promo_valid then
      seat_status_value:='Confirmed'; payment_status_value:='Paid'; registration_status_value:='Confirmed & Paid'; ticket_status_value:='Valid';
    else
      seat_status_value:='Reserved – Payment Pending'; payment_status_value:='Payment Pending'; registration_status_value:='Reserved – Payment Pending'; ticket_status_value:='Not Valid';
    end if;
  else
    seat_status_value:='Pending';
    if promo_valid then
      payment_status_value:='Paid'; registration_status_value:='Paid – Waiting for Seat'; ticket_status_value:='Not Valid';
    else
      payment_status_value:='Payment Pending'; registration_status_value:='Pending – Waiting for Seat'; ticket_status_value:='Not Valid';
    end if;
  end if;

  reg_no := nextval('public.registration_number_seq');
  reg_id := 'FG26-' || lpad(reg_no::text,6,'0');
  qr_text := json_build_object('registrationId',reg_id,'event',es.event_name)::text;

  insert into public.registrations(
    registration_id, registration_number, main_participant, nationality, gender, main_age_group, mobile, email,
    participants, fee_breakdown, total_participants, entry_fee, total_amount, payment_method, promo_code_used,
    discount_amount, rating, feedback_comment, seat_status, payment_status, registration_status, ticket_status, qr_data
  ) values (
    reg_id, reg_no, main_name, nationality, main_gender, main_age, mobile, email, extras, fee_breakdown, total_people,
    total_before_discount, total_amount, payment_method_value, case when promo_valid then promo_input else '' end,
    discount_amount, rating_value, feedback_value, seat_status_value, payment_status_value, registration_status_value, ticket_status_value, qr_text
  ) returning * into rec;

  if promo_valid and total_amount = 0 then
    insert into public.admin_logs(action,details) values('FREE_PROMO_REGISTRATION',rec.registration_id || ' used the Free Promo Code.');
  end if;

  return jsonb_build_object(
    'registration', jsonb_build_object(
      'registrationId',rec.registration_id,'createdAt',rec.created_at,'mainParticipant',rec.main_participant,'nationality',rec.nationality,'gender',rec.gender,'mainAgeGroup',rec.main_age_group,'mobile',rec.mobile,'email',rec.email,'emailToken',rec.email_token,'participants',rec.participants,'feeBreakdown',rec.fee_breakdown,'totalParticipants',rec.total_participants,'entryFee',rec.entry_fee,'discountAmount',rec.discount_amount,'totalAmount',rec.total_amount,'paymentMethod',rec.payment_method,'promoCodeUsed',rec.promo_code_used,'rating',rec.rating,'feedbackComment',rec.feedback_comment,'seatStatus',rec.seat_status,'paymentStatus',rec.payment_status,'registrationStatus',rec.registration_status,'ticketStatus',rec.ticket_status,'checkedIn',rec.checked_in,'qrData',rec.qr_data
    ),
    'availability',public.get_availability(),'emailEnabled',es.confirmation_email_enabled
  );
end;
$$;
grant execute on function public.create_registration(jsonb) to anon, authenticated;

create or replace function public.find_registration(p_query text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  q text := regexp_replace(trim(coalesce(p_query,'')), '[^0-9A-Za-z_-]', '', 'g');
  rec public.registrations;
begin
  if q ~ '^[0-9]{9}$' then q := '0' || q; end if;
  select * into rec from public.registrations where upper(registration_id)=upper(q) or mobile=q order by created_at desc limit 1;
  if not found then raise exception 'Registration not found.'; end if;
  return jsonb_build_object('registrationId',rec.registration_id,'createdAt',rec.created_at,'mainParticipant',rec.main_participant,'nationality',rec.nationality,'gender',rec.gender,'mainAgeGroup',rec.main_age_group,'mobile',rec.mobile,'participants',rec.participants,'feeBreakdown',rec.fee_breakdown,'totalParticipants',rec.total_participants,'entryFee',rec.entry_fee,'discountAmount',rec.discount_amount,'totalAmount',rec.total_amount,'paymentMethod',rec.payment_method,'promoCodeUsed',rec.promo_code_used,'rating',rec.rating,'feedbackComment',rec.feedback_comment,'seatStatus',rec.seat_status,'paymentStatus',rec.payment_status,'registrationStatus',rec.registration_status,'ticketStatus',rec.ticket_status,'checkedIn',rec.checked_in,'qrData',rec.qr_data);
end;
$$;
grant execute on function public.find_registration(text) to anon, authenticated;

create or replace function public.process_waiting_list_locked()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  es public.event_settings;
  occupied integer := 0;
  rec public.registrations;
begin
  select * into es from public.event_settings where id=1 for update;
  select coalesce(sum(total_participants),0)::int into occupied
  from public.registrations where seat_status in ('Reserved – Payment Pending','Confirmed');

  for rec in
    select * from public.registrations
    where seat_status='Pending'
    order by created_at asc
    for update
  loop
    exit when occupied + rec.total_participants > es.total_seats;
    occupied := occupied + rec.total_participants;
    if rec.payment_status='Paid' then
      update public.registrations
      set seat_status='Confirmed', registration_status='Confirmed & Paid', ticket_status='Valid', updated_at=now()
      where registration_id=rec.registration_id;
    else
      update public.registrations
      set seat_status='Reserved – Payment Pending', registration_status='Reserved – Payment Pending', ticket_status='Not Valid', updated_at=now()
      where registration_id=rec.registration_id;
    end if;
  end loop;
end;
$$;

create or replace function public.sync_registration_income()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  insert into public.finance_transactions(transaction_date,transaction_type,category,description,amount,reference,notes,created_by,source_type,source_id)
  select r.created_at::date,'Income','Registration Fee','Registration income - '||r.registration_id,r.total_amount,r.registration_id,'Automatically added from paid registration',auth.uid(),'Registration',r.registration_id
  from public.registrations r
  where r.payment_status='Paid' and r.total_amount>0
    and not exists(select 1 from public.finance_transactions t where t.source_type='Registration' and t.source_id=r.registration_id);
  delete from public.finance_transactions t
  where t.source_type='Registration'
    and not exists(select 1 from public.registrations r where r.registration_id=t.source_id and r.payment_status='Paid' and r.total_amount>0);
end;
$$;
grant execute on function public.sync_registration_income() to authenticated;

create or replace function public.admin_dashboard()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  regs jsonb; logs jsonb; es public.event_settings;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  perform public.sync_registration_income();
  select * into es from public.event_settings where id=1;
  select coalesce(jsonb_agg(q.x order by q.created_at desc),'[]'::jsonb) into regs
  from (select jsonb_build_object('registrationId',r.registration_id,'createdAt',r.created_at,'mainParticipant',r.main_participant,'nationality',r.nationality,'gender',r.gender,'mainAgeGroup',r.main_age_group,'mobile',r.mobile,'email',r.email,'participants',r.participants,'feeBreakdown',r.fee_breakdown,'totalParticipants',r.total_participants,'entryFee',r.entry_fee,'discountAmount',r.discount_amount,'totalAmount',r.total_amount,'paymentMethod',r.payment_method,'promoCodeUsed',r.promo_code_used,'seatStatus',r.seat_status,'paymentStatus',r.payment_status,'registrationStatus',r.registration_status,'ticketStatus',r.ticket_status,'checkedIn',r.checked_in,'checkedInAt',r.checked_in_at,'qrData',r.qr_data,'emailToken',r.email_token,'rating',r.rating,'feedbackComment',r.feedback_comment) x, r.created_at from public.registrations r) q;
  select coalesce(jsonb_agg(jsonb_build_object('date',l.created_at,'user',coalesce(u.email,'ADMIN'),'action',l.action,'details',l.details) order by l.created_at desc),'[]'::jsonb) into logs from public.admin_logs l left join auth.users u on u.id=l.user_id;
  return jsonb_build_object('settings',jsonb_build_object('eventName',es.event_name,'eventDate',es.event_date,'venue',es.venue,'totalSeats',es.total_seats,'fees',es.fees,'logoUrl',es.logo_url,'promoCode',es.promo_code,'whatsappGroupLink',es.whatsapp_group_link,'confirmationEmailEnabled',es.confirmation_email_enabled,'emailSubject',es.email_subject,'emailBody',es.email_body),'availability',public.get_availability(),'registrations',regs,'adminLog',logs,'finance',public.get_finance_dashboard());
end;
$$;
grant execute on function public.admin_dashboard() to authenticated;
revoke all on function public.sync_registration_income() from public;
grant execute on function public.sync_registration_income() to authenticated;

create or replace function public.admin_save_event_settings(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare es public.event_settings;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  update public.event_settings set event_name=trim(coalesce(p_data->>'eventName',event_name)),event_date=coalesce(p_data->>'eventDate',event_date),venue=coalesce(p_data->>'venue',venue),total_seats=greatest(coalesce((p_data->>'totalSeats')::int,total_seats),0),logo_url=coalesce(nullif(p_data->>'logoUrl',''),logo_url),promo_code=upper(trim(coalesce(p_data->>'promoCode',promo_code))),fees=jsonb_build_object('Infant',greatest(coalesce((p_data->'fees'->>'Infant')::numeric,0),0),'Child',greatest(coalesce((p_data->'fees'->>'Child')::numeric,0),0),'Teenager',greatest(coalesce((p_data->'fees'->>'Teenager')::numeric,0),0),'Adult',greatest(coalesce((p_data->'fees'->>'Adult')::numeric,0),0),'Senior',greatest(coalesce((p_data->'fees'->>'Senior')::numeric,0),0)),updated_at=now() where id=1 returning * into es;
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'SAVE_EVENT_SETTINGS','Event name, date, venue, seats, fees, promo code and logo updated.');
  return public.admin_dashboard();
end;
$$;
grant execute on function public.admin_save_event_settings(jsonb) to authenticated;

create or replace function public.admin_save_communication_settings(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  es public.event_settings;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  update public.event_settings
  set whatsapp_group_link = coalesce(p_data->>'whatsappGroupLink', whatsapp_group_link),
      confirmation_email_enabled = coalesce((p_data->>'confirmationEmailEnabled')::boolean, confirmation_email_enabled),
      email_subject = coalesce(p_data->>'emailSubject', email_subject),
      email_body = coalesce(p_data->>'emailBody', email_body),
      updated_at=now()
  where id=1 returning * into es;
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'SAVE_COMMUNICATION_SETTINGS','WhatsApp/email communication settings updated.');
  return public.admin_dashboard();
end;
$$;

grant execute on function public.admin_save_communication_settings(jsonb) to authenticated;

create or replace function public.admin_update_payment_status(p_registration_id text,p_status text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare reg public.registrations; es public.event_settings; occupied integer:=0; new_seat text; new_reg_status text;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  if p_status not in ('Payment Pending','Paid','Failed','Expired','Cancelled') then raise exception 'Invalid payment status.'; end if;
  select * into es from public.event_settings where id=1 for update;
  select * into reg from public.registrations where registration_id=upper(p_registration_id) for update;
  if not found then raise exception 'Registration not found.'; end if;
  if p_status='Paid' then
    if reg.seat_status='Pending' then
      perform public.process_waiting_list_locked();
      select * into reg from public.registrations where registration_id=upper(p_registration_id) for update;
      if reg.seat_status='Pending' then update public.registrations set payment_status='Paid',registration_status='Paid – Waiting for Seat',ticket_status='Not Valid',updated_at=now() where registration_id=reg.registration_id;
      else update public.registrations set payment_status='Paid',seat_status='Confirmed',registration_status='Confirmed & Paid',ticket_status='Valid',updated_at=now() where registration_id=reg.registration_id; end if;
    else update public.registrations set payment_status='Paid',seat_status='Confirmed',registration_status='Confirmed & Paid',ticket_status='Valid',updated_at=now() where registration_id=reg.registration_id; end if;
  elsif p_status='Payment Pending' then
    select coalesce(sum(total_participants),0)::int into occupied from public.registrations where seat_status in ('Reserved – Payment Pending','Confirmed') and registration_id<>reg.registration_id;
    if occupied+reg.total_participants<=es.total_seats then new_seat='Reserved – Payment Pending'; new_reg_status='Reserved – Payment Pending'; else new_seat='Pending'; new_reg_status='Pending – Waiting for Seat'; end if;
    update public.registrations set payment_status='Payment Pending',seat_status=new_seat,registration_status=new_reg_status,ticket_status='Not Valid',updated_at=now() where registration_id=reg.registration_id;
  else
    update public.registrations set payment_status=p_status,seat_status='Released',registration_status=case when p_status='Failed' then 'Payment Failed' when p_status='Expired' then 'Payment Expired' else 'Cancelled' end,ticket_status='Not Valid',updated_at=now() where registration_id=reg.registration_id;
    perform public.process_waiting_list_locked();
  end if;
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'UPDATE_PAYMENT_STATUS',format('%s → %s',reg.registration_id,p_status));
  perform public.sync_registration_income();
  return public.admin_dashboard();
end;
$$;
grant execute on function public.admin_update_payment_status(text,text) to authenticated;

create or replace function public.admin_check_in(p_registration_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare r public.registrations;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  select * into r from public.registrations where registration_id=upper(p_registration_id) for update;
  if not found then raise exception 'Registration not found.'; end if;
  if r.ticket_status <> 'Valid' then raise exception 'Ticket is not valid.'; end if;
  update public.registrations set checked_in=true, checked_in_at=now(), updated_at=now() where registration_id=r.registration_id;
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'CHECK_IN',r.registration_id || ' checked in.');
  return true;
end;
$$;

grant execute on function public.admin_check_in(text) to authenticated;

create or replace function public.admin_verify_entry(p_registration_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare r public.registrations;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  select * into r from public.registrations where registration_id=upper(p_registration_id);
  if not found then raise exception 'Registration not found.'; end if;
  return jsonb_build_object('registrationId',r.registration_id,'mainParticipant',r.main_participant,'paymentStatus',r.payment_status,'registrationStatus',r.registration_status,'ticketStatus',r.ticket_status,'checkedIn',r.checked_in,'qrData',r.qr_data);
end;
$$;

grant execute on function public.admin_verify_entry(text) to authenticated;

create or replace function public.admin_delete_registration(p_registration_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  delete from public.registrations where registration_id=upper(p_registration_id);
  perform public.process_waiting_list_locked();
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'DELETE_REGISTRATION',upper(p_registration_id));
  return public.admin_dashboard();
end;
$$;

grant execute on function public.admin_delete_registration(text) to authenticated;

create or replace function public.admin_clear_registrations()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  delete from public.registrations;
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'CLEAR_REGISTRATION_DATA','All registrations cleared; event settings and logs preserved.');
  return public.admin_dashboard();
end;
$$;

grant execute on function public.admin_clear_registrations() to authenticated;

create or replace function public.admin_delete_all_data()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  delete from public.registrations;
  delete from public.admin_logs;
  return public.admin_dashboard();
end;
$$;

grant execute on function public.admin_delete_all_data() to authenticated;

-- Keep updated_at current when admin-side direct changes are made.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists registrations_touch_updated_at on public.registrations;
create trigger registrations_touch_updated_at before update on public.registrations for each row execute function public.touch_updated_at();

drop trigger if exists event_settings_touch_updated_at on public.event_settings;
create trigger event_settings_touch_updated_at before update on public.event_settings for each row execute function public.touch_updated_at();

-- RLS
alter table public.event_settings enable row level security;
alter table public.admin_users enable row level security;
alter table public.registrations enable row level security;
alter table public.admin_logs enable row level security;

-- Remove broad default permissions; RPC functions above are the public API.
revoke all on table public.event_settings from anon, authenticated;
revoke all on table public.registrations from anon, authenticated;
revoke all on table public.admin_logs from anon, authenticated;
revoke all on table public.admin_users from anon, authenticated;

grant select on table public.admin_users to authenticated;
grant select on table public.event_settings to authenticated;
grant select, insert, update, delete on table public.registrations to authenticated;
grant select, insert on table public.admin_logs to authenticated;

drop policy if exists admin_users_self_select on public.admin_users;
create policy admin_users_self_select on public.admin_users
for select to authenticated
using ((select auth.uid()) = id);

drop policy if exists event_settings_admin_select on public.event_settings;
create policy event_settings_admin_select on public.event_settings
for select to authenticated
using (public.is_admin());

drop policy if exists registrations_admin_all on public.registrations;
create policy registrations_admin_all on public.registrations
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists admin_logs_admin_all on public.admin_logs;
create policy admin_logs_admin_all on public.admin_logs
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Function permissions for public API
revoke all on function public.create_registration(jsonb) from public;
grant execute on function public.create_registration(jsonb) to anon, authenticated;
revoke all on function public.find_registration(text) from public;
grant execute on function public.find_registration(text) to anon, authenticated;
revoke all on function public.get_public_settings() from public;
grant execute on function public.get_public_settings() to anon, authenticated;
revoke all on function public.get_availability() from public;
grant execute on function public.get_availability() to anon, authenticated;

-- Admin RPCs
revoke all on function public.admin_dashboard() from public;
grant execute on function public.admin_dashboard() to authenticated;
revoke all on function public.admin_save_event_settings(jsonb) from public;
grant execute on function public.admin_save_event_settings(jsonb) to authenticated;
revoke all on function public.admin_save_communication_settings(jsonb) from public;
grant execute on function public.admin_save_communication_settings(jsonb) to authenticated;
revoke all on function public.admin_update_payment_status(text,text) from public;
grant execute on function public.admin_update_payment_status(text,text) to authenticated;
revoke all on function public.admin_check_in(text) from public;
grant execute on function public.admin_check_in(text) to authenticated;
revoke all on function public.admin_verify_entry(text) from public;
grant execute on function public.admin_verify_entry(text) to authenticated;
revoke all on function public.admin_delete_registration(text) from public;
grant execute on function public.admin_delete_registration(text) to authenticated;
revoke all on function public.admin_clear_registrations() from public;
grant execute on function public.admin_clear_registrations() to authenticated;
revoke all on function public.admin_delete_all_data() from public;
grant execute on function public.admin_delete_all_data() to authenticated;

-- Manual admin setup after creating the admin user in Supabase Auth:
-- insert into public.admin_users(id, role) values ('YOUR-AUTH-USER-UUID','admin') on conflict (id) do update set role='admin';


-- ============================================================
-- FINANCE MODULE: Opening Balance, Budget, Income & Expenses
-- ============================================================

create table if not exists public.finance_opening_balance (
  id integer primary key default 1 check (id = 1),
  amount numeric(14,2) not null default 0,
  as_of_date date,
  notes text not null default '',
  updated_at timestamptz not null default now()
);
insert into public.finance_opening_balance (id, amount) values (1,0)
on conflict (id) do nothing;

create table if not exists public.finance_budget_items (
  id bigint generated by default as identity primary key,
  category text not null,
  description text not null default '',
  budget_amount numeric(14,2) not null default 0 check (budget_amount >= 0),
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists finance_budget_items_active_idx on public.finance_budget_items(active);

create table if not exists public.finance_transactions (
  id bigint generated by default as identity primary key,
  transaction_date date not null default current_date,
  transaction_type text not null check (transaction_type in ('Income','Expense')),
  category text not null,
  description text not null default '',
  amount numeric(14,2) not null check (amount >= 0),
  reference text not null default '',
  notes text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  source_type text not null default '',
  source_id text not null default ''
);
create index if not exists finance_transactions_date_idx on public.finance_transactions(transaction_date desc, id desc);
create index if not exists finance_transactions_type_idx on public.finance_transactions(transaction_type);

-- Existing-install upgrades (safe to re-run). Moved here so all referenced tables already exist.
alter table public.event_settings add column if not exists logo_url text not null default 'logo.svg';
alter table public.event_settings add column if not exists promo_code text not null default 'FREE2026';
alter table public.registrations add column if not exists promo_code_used text not null default '';
alter table public.registrations add column if not exists discount_amount numeric(12,2) not null default 0;
alter table public.registrations add column if not exists rating smallint;
alter table public.registrations add column if not exists feedback_comment text not null default '';
alter table public.finance_transactions add column if not exists source_type text not null default '';
alter table public.finance_transactions add column if not exists source_id text not null default '';
update public.event_settings
set event_name = case when event_name = 'Mega Family Gathering 2026' then 'Mega Youth Family Gathering 2026' else event_name end,
    email_subject = case when email_subject like 'Mega Family Gathering 2026%' then 'Mega Youth Family Gathering 2026 – Registration Confirmation' else email_subject end,
    logo_url = coalesce(nullif(logo_url,''),'logo.svg'),
    promo_code = coalesce(nullif(promo_code,''),'FREE2026')
where id=1;

alter table public.registrations drop constraint if exists registrations_payment_method_check;
alter table public.registrations add constraint registrations_payment_method_check check (payment_method in ('Cash','Promo Code'));



delete from public.finance_transactions a using public.finance_transactions b where a.id>b.id and a.source_type='Registration' and b.source_type='Registration' and a.source_id=b.source_id;
create unique index if not exists finance_transactions_registration_source_uq on public.finance_transactions(source_type,source_id) where source_type='Registration' and source_id<>'';

create or replace function public.get_finance_dashboard()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  opening jsonb;
  budget jsonb;
  tx jsonb;
  opening_amount numeric(14,2) := 0;
  income_total numeric(14,2) := 0;
  expense_total numeric(14,2) := 0;
  budget_total numeric(14,2) := 0;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;

  select jsonb_build_object(
    'amount', ob.amount,
    'asOfDate', ob.as_of_date,
    'notes', ob.notes
  ), ob.amount
  into opening, opening_amount
  from public.finance_opening_balance ob
  where ob.id=1;

  if opening is null then
    opening := jsonb_build_object('amount',0,'asOfDate',null,'notes','');
    opening_amount := 0;
  end if;

  select coalesce(sum(budget_amount) filter (where active),0)
  into budget_total
  from public.finance_budget_items;

  select
    coalesce(sum(amount) filter (where transaction_type='Income'),0),
    coalesce(sum(amount) filter (where transaction_type='Expense'),0)
  into income_total, expense_total
  from public.finance_transactions;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', b.id,
    'category', b.category,
    'description', b.description,
    'budgetAmount', b.budget_amount,
    'active', b.active,
    'createdAt', b.created_at
  ) order by b.category, b.id), '[]'::jsonb)
  into budget
  from public.finance_budget_items b;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', t.id,
    'transactionDate', t.transaction_date,
    'transactionType', t.transaction_type,
    'category', t.category,
    'description', t.description,
    'amount', t.amount,
    'reference', t.reference,
    'notes', t.notes,
    'createdAt', t.created_at
  ) order by t.transaction_date desc, t.id desc), '[]'::jsonb)
  into tx
  from public.finance_transactions t;

  return jsonb_build_object(
    'openingBalance', opening,
    'budgetTotal', budget_total,
    'incomeTotal', income_total,
    'expenseTotal', expense_total,
    'closingBalance', opening_amount + income_total - expense_total,
    'budgetRemaining', budget_total - expense_total,
    'budgetItems', budget,
    'transactions', tx
  );
end;
$$;
grant execute on function public.get_finance_dashboard() to authenticated;

create or replace function public.admin_save_opening_balance(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_amount numeric(14,2);
  v_date date;
  v_notes text;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  v_amount := greatest(coalesce((p_data->>'amount')::numeric,0),0);
  v_date := nullif(trim(coalesce(p_data->>'asOfDate','')), '')::date;
  v_notes := coalesce(p_data->>'notes','');
  insert into public.finance_opening_balance(id,amount,as_of_date,notes,updated_at)
  values(1,v_amount,v_date,v_notes,now())
  on conflict (id) do update set amount=excluded.amount, as_of_date=excluded.as_of_date, notes=excluded.notes, updated_at=now();
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'SAVE_OPENING_BALANCE',format('Opening balance set to SAR %s.',to_char(v_amount,'FM999999990.00')));
  return public.admin_dashboard();
end;
$$;
grant execute on function public.admin_save_opening_balance(jsonb) to authenticated;

create or replace function public.admin_upsert_budget_item(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_category text;
  v_description text;
  v_amount numeric(14,2);
  v_active boolean;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  v_category := trim(coalesce(p_data->>'category',''));
  v_description := trim(coalesce(p_data->>'description',''));
  v_amount := greatest(coalesce((p_data->>'budgetAmount')::numeric,0),0);
  v_active := coalesce((p_data->>'active')::boolean,true);
  if v_category='' then raise exception 'Budget category is required.'; end if;
  if nullif(trim(coalesce(p_data->>'id','')), '') is not null then
    v_id := (p_data->>'id')::bigint;
    update public.finance_budget_items
      set category=v_category, description=v_description, budget_amount=v_amount, active=v_active, updated_at=now()
      where id=v_id;
    if not found then raise exception 'Budget item not found.'; end if;
  else
    insert into public.finance_budget_items(category,description,budget_amount,active,created_by)
    values(v_category,v_description,v_amount,v_active,auth.uid()) returning id into v_id;
  end if;
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'SAVE_BUDGET_ITEM',format('%s / SAR %s',v_category,to_char(v_amount,'FM999999990.00')));
  return public.admin_dashboard();
end;
$$;
grant execute on function public.admin_upsert_budget_item(jsonb) to authenticated;

create or replace function public.admin_delete_budget_item(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  delete from public.finance_budget_items where id=p_id;
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'DELETE_BUDGET_ITEM',p_id::text);
  return public.admin_dashboard();
end;
$$;
grant execute on function public.admin_delete_budget_item(bigint) to authenticated;

create or replace function public.admin_add_finance_transaction(p_data jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_date date;
  v_type text;
  v_category text;
  v_description text;
  v_amount numeric(14,2);
  v_reference text;
  v_notes text;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  v_date := coalesce(nullif(trim(coalesce(p_data->>'transactionDate','')), '')::date, current_date);
  v_type := trim(coalesce(p_data->>'transactionType',''));
  v_category := trim(coalesce(p_data->>'category',''));
  v_description := trim(coalesce(p_data->>'description',''));
  v_amount := greatest(coalesce((p_data->>'amount')::numeric,0),0);
  v_reference := trim(coalesce(p_data->>'reference',''));
  v_notes := trim(coalesce(p_data->>'notes',''));
  if v_type not in ('Income','Expense') then raise exception 'Transaction type must be Income or Expense.'; end if;
  if v_category='' then raise exception 'Transaction category is required.'; end if;
  if v_amount <= 0 then raise exception 'Transaction amount must be greater than zero.'; end if;
  insert into public.finance_transactions(transaction_date,transaction_type,category,description,amount,reference,notes,created_by)
  values(v_date,v_type,v_category,v_description,v_amount,v_reference,v_notes,auth.uid());
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'ADD_FINANCE_TRANSACTION',format('%s | %s | SAR %s',v_type,v_category,to_char(v_amount,'FM999999990.00')));
  return public.admin_dashboard();
end;
$$;
grant execute on function public.admin_add_finance_transaction(jsonb) to authenticated;

create or replace function public.admin_delete_finance_transaction(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  delete from public.finance_transactions where id=p_id;
  insert into public.admin_logs(user_id,action,details) values(auth.uid(),'DELETE_FINANCE_TRANSACTION',p_id::text);
  return public.admin_dashboard();
end;
$$;
grant execute on function public.admin_delete_finance_transaction(bigint) to authenticated;

alter table public.finance_opening_balance enable row level security;
alter table public.finance_budget_items enable row level security;
alter table public.finance_transactions enable row level security;
revoke all on table public.finance_opening_balance from anon, authenticated;
revoke all on table public.finance_budget_items from anon, authenticated;
revoke all on table public.finance_transactions from anon, authenticated;
drop policy if exists finance_opening_balance_admin_all on public.finance_opening_balance;
create policy finance_opening_balance_admin_all on public.finance_opening_balance for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists finance_budget_items_admin_all on public.finance_budget_items;
create policy finance_budget_items_admin_all on public.finance_budget_items for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists finance_transactions_admin_all on public.finance_transactions;
create policy finance_transactions_admin_all on public.finance_transactions for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop trigger if exists finance_budget_items_touch_updated_at on public.finance_budget_items;
create trigger finance_budget_items_touch_updated_at before update on public.finance_budget_items for each row execute function public.touch_updated_at();

-- Update Admin Dashboard to include the finance section.
create or replace function public.admin_dashboard()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  regs jsonb;
  logs jsonb;
  es public.event_settings;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;
  select * into es from public.event_settings where id=1;
  select coalesce(jsonb_agg(q.x order by q.created_at desc), '[]'::jsonb) into regs
  from (
    select jsonb_build_object(
      'registrationId',r.registration_id,'createdAt',r.created_at,'mainParticipant',r.main_participant,'nationality',r.nationality,'gender',r.gender,'mainAgeGroup',r.main_age_group,
      'mobile',r.mobile,'email',r.email,'participants',r.participants,'feeBreakdown',r.fee_breakdown,'totalParticipants',r.total_participants,'entryFee',r.entry_fee,'totalAmount',r.total_amount,
      'paymentMethod',r.payment_method,'seatStatus',r.seat_status,'paymentStatus',r.payment_status,'registrationStatus',r.registration_status,'ticketStatus',r.ticket_status,'checkedIn',r.checked_in,'checkedInAt',r.checked_in_at,'qrData',r.qr_data,
      'emailToken',r.email_token
    ) as x, r.created_at from public.registrations r
  ) q;
  select coalesce(jsonb_agg(jsonb_build_object('date',l.created_at,'user',coalesce(u.email,'ADMIN'),'action',l.action,'details',l.details) order by l.created_at desc), '[]'::jsonb)
  into logs from public.admin_logs l left join auth.users u on u.id=l.user_id;

  return jsonb_build_object(
    'settings', jsonb_build_object('eventName',es.event_name,'eventDate',es.event_date,'venue',es.venue,'totalSeats',es.total_seats,'fees',es.fees,'whatsappGroupLink',es.whatsapp_group_link,'confirmationEmailEnabled',es.confirmation_email_enabled,'emailSubject',es.email_subject,'emailBody',es.email_body),
    'availability', public.get_availability(),
    'registrations', regs,
    'adminLog', logs,
    'finance', public.get_finance_dashboard()
  );
end;
$$;
grant execute on function public.admin_dashboard() to authenticated;



-- ============================================================
-- FINAL INSTALL / UPGRADE VERIFICATION
-- ============================================================
do $$
begin
  if to_regclass('public.event_settings') is null
     or to_regclass('public.admin_users') is null
     or to_regclass('public.registrations') is null
     or to_regclass('public.admin_logs') is null
     or to_regclass('public.finance_opening_balance') is null
     or to_regclass('public.finance_budget_items') is null
     or to_regclass('public.finance_transactions') is null then
    raise exception 'Required Mega Youth Family Gathering tables are missing.';
  end if;
  if not exists (
    select 1
    from pg_proc p
    join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public'
      and p.proname='bootstrap_first_admin'
      and pg_get_function_identity_arguments(p.oid)=''
  ) then
    raise exception 'bootstrap_first_admin() is missing. Please run this complete SQL file.';
  end if;
end $$;
select 'OK - Mega Youth Family Gathering 2026 database is installed/upgraded.' as setup_status;
